FORMAT: 1A

# Unacademic
UnAcademic API is a *academic content curation* service.

# Group Paths
Notes related resources of the **Paths API**

## Path [/paths/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Path to perform action with. Has example value.

### Get a single Path [GET]
+ Response 200 (application/json)

         {
            "id":123123,
            "curator":"Jan Hein",
            "title": "Coding the Humanities",
            "image_url": "http://amaridesplays.files.wordpress.com/2013/10/coding-dojo.jpg",
            "summary": "A path about web technologies",
            "description": "You must be anxious to dive into the wonderful world of web programming. But the first thing we want you to do has sadly / luckily nothing to do with  code. The Citywalk will combine the knowledge you will get from the first  tutorials. Read on to find out how exactly you are going to do that.\n",
            "version": "0.0.1",
            "license": "MIT",
            "keywords": ["web","tech"],
            "forks": [123124,123126],
            "forked_from": null,
            "learners": [2, 7, 15],
            "waypoints": [
                { 
                    "id": 1,
                    "curator": "yeehaa",
                    "curator_org": "University of Amsterdam",
                    "contributors": "",
                    "title": "CSS",
                    "image_url": "img/objectives/css/logo.svg",
                    "version": "1.0.1",
                    "learners": [2, 7, 15],
                    "description": "This is the introduction to CSS (cascading style sheets). A CSS file allows  you to separate your website's markup content from its style. As always you  use your HTML file to arrange the content, but all of the presentation  (fonts, colors, background, borders, text formatting, link effects & so on...)  are accomplished within a CSS file.\n",
                    "summary": "CSS allows you to separate your website's styling from its HTML content. \n",
                    "keywords": [ "cth-design" ],
                    "objectives": [ 1, 2, 3, 4 ] 
                },
                { 
                    "id": 2,
                    "curator": "yeehaa",
                    "curator_org": "University of Amsterdam",
                    "contributors": "",
                    "title": "City Walk",
                    "version": "0.0.1",
                    "learners": [2, 7, 15],
                    "description": "You must be anxious to dive into the wonderful world of web programming. But the first thing we want you to do has sadly / luckily nothing to do with  code. The Citywalk will combine the knowledge you will get from the first  tutorials. Read on to find out how exactly you are going to do that.\n",
                    "summary": "Get some last contact with the real world, before you disappear into its  virtual counterpart.\n",
                    "keywords": [ "cth-general" ],
                    "objectives": [ 5, 6, 7 ]
                },
                {   "id": 3,
                    "curator": "yeehaa",
                    "curator_org": "University of Amsterdam",
                    "contributors": "",
                    "title": "Gists",
                    "version": "0.0.1",
                    "learners": [2, 7, 15],
                    "description": "You would think one way to share code with your peers and/or friends would  be by e-mail. But mailing one's code is a hassle when you have to deal with lots of different files and endless lines of code. Another way is to place  these on Github, a website made for and by programmers to store and share code. Github offers two ways to do that. The first is making a repository. More on this will follow later. The second way is Gist, particulary handy for code  snippets and a lot easier -though with some limitations.\n",
                    "summary": "Sharing code can be quite a hassle. Github offers solutions to this problem.\n",
                    "keywords": [ "cth-workflow" ],
                    "objectives": [ 8, 9, 10, 11 ] 
                },
                {   "id": 4,
                    "curator": "yeehaa",
                    "curator_org": "University of Amsterdam",
                    "contributors": "",
                    "title": "HTML",
                    "version": "0.0.1",
                    "learners": [2, 7, 15],
                    "description": "HTML stands for Hypertext Markup Language. When you look at a web page on a  web browser you see, at the simplest level, words. HTML instructs a web  browser what content to display. In many cases a page also displays images  or maybe video clips.  HTML defines and separates 'content' (words, images, audio, video, and so  on) from 'presentation' (how to display a specific type of content). HTML  uses a pre-defined set of elements to identify content types.\n",
                    "summary": "HTML gives directions to the web browser on what content to display.  It uses a set of elements to identify content types.\n",
                    "keywords": [ "cth-markup" ],
                    "objectives": [ 12, 13, 14, 15 ] 
                },
                {   "id": 5,
                    "curator": "yeehaa",
                    "curator_org": "University of Amsterdam",
                    "contributors": "",
                    "title": "DOM",
                    "version": "0.0.1",
                    "learners": [2, 7, 15],
                    "description": "The DOM is a different representation of the HTML in the browser.  In the DOM you can see the various objects on a page and how they relate to each other in a tree structure. The DOM can be viewed and manipulated using the javascript console in your browser. Every browser has a console, so don't worry about having to install yet another program on your computer.\n",
                    "summary": "The DOM (Document Object Model) is the structural representation of an HTML document\n",
                    "keywords": [ "cth-markup" ],
                    "objectives": [ 16, 17, 18, 19, 20 ] 
                }
            ]
        }

### Delete a Path [DELETE]
+ Response 204 (application/json)

## Paths Collection [/paths]
### List all Paths [GET]
+ Response 200 (application/json)

         [
            {
                "id": 123123,
                "curator":"Jan Hein",
                "title": "Coding the Humanities",
                "description": "A path about web technologies",
                "image_url": "http://amaridesplays.files.wordpress.com/2013/10/coding-dojo.jpg",
                "version": "0.0.1",
                "license": "MIT",
                "keywords": ["web","tech"],
                "forks": [123124,123126],
                "forked_from": null,
                "places": [1233, 7003, 110],
                "learners": [3, 10, 28, 33]
            },
            {
                "id": 123124,
                "curator":"Johanna",
                "title": "Augmenting Masterpieces",
                "description": "A path about web technologies",
                "image_url": "http://fc00.deviantart.net/fs70/f/2012/122/6/c/pixel_art__masterpiece_series__by_joojaebum-d4yd91s.jpg",
                "version": "1.2.3",
                "license": "MIT",
                "keywords": ["museums","design thinking"],
                "forks": [],
                "forked_from": [123123],
                "places": [1233],
                "learners": [3, 19, 7, 4]
            },
            {
                "id": 123126,
                "curator":"Marijn",
                "title": "Digging into Data",
                "description": "A path about web technologies",
                "image_url": "https://c2.staticflickr.com/6/5044/5279928246_252951a615.jpg",
                "version": "1.5.1",
                "license": "MIT",
                "keywords": ["data","search"],
                "forks": [],
                "forked_from": [123123],
                "places": [1233,7003, 110, 9999],
                "learners": [2, 5, 19]
            },
            {
                "id": 123144,
                "curator":"Charlotte",
                "title": "Content Strategy for Academics",
                "description": "A path about web technologies",
                "image_url": "http://vignette2.wikia.nocookie.net/cardfight/images/a/ab/Photo-feather-pen-784257.jpg/revision/latest?cb=20120911073258",
                "version": "2.2.9",
                "license": "MIT",
                "keywords": ["content","strategy"],
                "forks": [],
                "forked_from": null,
                "places": [],
                "learners": []
            },
            {
                "id": 123128,
                "curator":"Nigel",
                "title": "MBA for Dummies",
                "description": "A path about web technologies",
                "image_url": "http://www.dumblittleman.com/wp-content/uploads/2014/05/Money.jpg",
                "version": "0.2.0",
                "license": "MIT",
                "keywords": ["business","money"],
                "forks": [],
                "forked_from": null,
                "places": [1233, 7003, 110],
                "learners": [3, 8, 10]
            }
        ]

### Create a Path [POST]
+ Request (application/json)

        {
            "curator":"Reika",
            "title": "Shopping without a Budget",
            "description": "A path about web technologies",
            "version": "1.2.3",
            "license": "MIT",
            "keywords": ["shopping","money"]
        }

+ Response 201 (application/json)

        {
            "id": 122128,
            "curator":"Reika",
            "title": "Shopping without a Budget",
            "description": "A path about web technologies",
            "version": "1.2.3",
            "license": "MIT",
            "keywords": ["shopping","money"]
        }

# Group Places
Places related resources of the **Unacademic API**

## Places [/places/{id}]
### Delete a Path [DELETE]
+ Response 204 (application/json)

## Places Collection [/places]
### List all Places [GET]
+ Response 200 (application/json)

        [
            { 
                "id": 1,
                "curator": "yeehaa",
                "curator_org": "University of Amsterdam",
                "contributors": "",
                "title": "CSS",
                "description": "This is the introduction to CSS (cascading style sheets). A CSS file allows  you to separate your website's markup content from its style. As always you  use your HTML file to arrange the content, but all of the presentation  (fonts, colors, background, borders, text formatting, link effects & so on...)  are accomplished within a CSS file.\n",
                "summary": "CSS allows you to separate your website's styling from its HTML content. \n",
                "version": null,
                "keywords": [ "cth-design" ],
                "objectives": [ 1, 2, 3, 4 ] 
            },
            { 
                "id": 2,
                "curator": "yeehaa",
                "curator_org": "University of Amsterdam",
                "contributors": "",
                "title": "City Walk",
                "description": "You must be anxious to dive into the wonderful world of web programming. But the first thing we want you to do has sadly / luckily nothing to do with  code. The Citywalk will combine the knowledge you will get from the first  tutorials. Read on to find out how exactly you are going to do that.\n",
                "summary": "Get some last contact with the real world, before you disappear into its  virtual counterpart.\n",
                "version": null,
                "keywords": [ "cth-general" ],
                "objectives": [ 5, 6, 7 ]
            },
            {   "id": 3,
                "curator": "yeehaa",
                "curator_org": "University of Amsterdam",
                "contributors": "",
                "title": "Gists",
                "description": "You would think one way to share code with your peers and/or friends would  be by e-mail. But mailing one's code is a hassle when you have to deal with lots of different files and endless lines of code. Another way is to place  these on Github, a website made for and by programmers to store and share code. Github offers two ways to do that. The first is making a repository. More on this will follow later. The second way is Gist, particulary handy for code  snippets and a lot easier -though with some limitations.\n",
                "summary": "Sharing code can be quite a hassle. Github offers solutions to this problem.\n",
                "version": null,
                "keywords": [ "cth-workflow" ],
                "objectives": [ 8, 9, 10, 11 ] 
            },
            {   "id": 4,
                "curator": "yeehaa",
                "curator_org": "University of Amsterdam",
                "contributors": "",
                "title": "HTML",
                "description": "HTML stands for Hypertext Markup Language. When you look at a web page on a  web browser you see, at the simplest level, words. HTML instructs a web  browser what content to display. In many cases a page also displays images  or maybe video clips.  HTML defines and separates 'content' (words, images, audio, video, and so  on) from 'presentation' (how to display a specific type of content). HTML  uses a pre-defined set of elements to identify content types.\n",
                "summary": "HTML gives directions to the web browser on what content to display.  It uses a set of elements to identify content types.\n",
                "version": null,
                "keywords": [ "cth-markup" ],
                "objectives": [ 12, 13, 14, 15 ] 
            },
            {   "id": 5,
                "curator": "yeehaa",
                "curator_org": "University of Amsterdam",
                "contributors": "",
                "title": "DOM",
                "description": "The DOM is a different representation of the HTML in the browser.  In the DOM you can see the various objects on a page and how they relate to each other in a tree structure. The DOM can be viewed and manipulated using the javascript console in your browser. Every browser has a console, so don't worry about having to install yet another program on your computer.\n",
                "summary": "The DOM (Document Object Model) is the structural representation of an HTML document\n",
                "version": null,
                "keywords": [ "cth-markup" ],
                "objectives": [ 16, 17, 18, 19, 20 ] 
            },
            {   "id": 6,
                "curator": "yeehaa",
                "curator_org": "University of Amsterdam",
                "contributors": "",
                "title": "Dev Tools",
                "description": "Very important tools to know are the developer tools in browsers. They are used for many things like bug testing and experimenting. You can also use it to see the perfomance of the site. You can view your HTML, CSS and script combined, and you can actively interact with it. Google has very nice implementations, which is one of the reasons why we use chrome as a standard browser.\n",
                "summary": "Very important tools to know are the development tools in browsers. They are used for many things like bug testing and experimenting.\n",
                "version": null,
                "keywords": [ "cth-workflow" ],
                "objectives": [ 21, 22, 23 ] 
            }
        ]

### Create a Place [POST]
+ Request (application/json)

        {
            "curator":"Reika",
            "title": "Shopping without a Budget",
            "description": "A path about web technologies",
            "version": "1.2.3",
            "license": "MIT",
            "keywords": ["shopping","money"]
        }

+ Response 201 (application/json)

        {
            "id": 122128,
            "curator":"Reika",
            "title": "Shopping without a Budget",
            "description": "A path about web technologies",
            "version": "1.2.3",
            "license": "MIT",
            "keywords": ["shopping","money"]
        }
